spring:
  application:
    name: accounts-service
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka-server/eureka/
spring.jmx.default-domain: com.eureka.service